//POSITION
export const SET_POSITIONRESULT = 'SET_POSITIONRESULT';
export const SET_POSITIONSTATUS = 'SET_POSITIONSTATUS';
export const SET_POSITIONAGAIN = 'SET_POSITIONAGAIN';
export const SET_POSITIONPLACESEARCH = 'SET_POSITIONPLACESEARCH';
export const SET_POSITIONSEARCHNEARBY = 'SET_POSITIONSEARCHNEARBY';

//userInfo
export const SET_USERNAME = 'SET_USERNAME';
export const SET_USERPHONE = 'SET_USERPHONE';
export const SET_USERADDRESSLIST = 'SET_USERADDRESSLIST';
export const SET_USERSELECTADDRESS = 'SET_USERSELECTADDRESS';
export const DELETE_USERADDRESSLIST = 'DELETE_USERADDRESSLIST';